export const itemsMobile = [
  {
    id: 1,
    titleid: '001',
    title: 'KATJO',
    slug: 'katjo',
    img: "/asset/img/KATJO.svg",
    imgnoir: "/asset/img/KATJOnoir.svg",
    category: 'application',
  },
  {
    id: 2,
    titleid: '002',
    title: 'PL@NET',
    slug: 'pl@net',
    img: "/asset/img/KATJO1.svg",
    imgnoir: "/asset/img/KATJO1noir.svg",
    category: 'application',
  },
  {
    id: 3,
    titleid: '003',
    title: 'HESTIA',
    slug: 'hestia',
    img: "/asset/img/KATJO3.svg",
    imgnoir: "/asset/img/KATJO3noir.svg",
    category: 'application',
  },
  {
    id: 4,
    titleid: '004',
    title: 'Brand Design',
    slug: 'branddesign',
    imgnoir: "/asset/img/KATJO2noir.svg",
    img: "/asset/img/KATJO4.svg",
    category: 'application',
  },
  {
    id: 5,
    titleid: '005',
    title: 'SUPERMOOD',
    slug: 'supermood',
    img: "/asset/img/KATJO2.svg",
    imgnoir: "/asset/img/KATJO4noir.svg",
    category: 'application',
  },
]
