export const items = [
  {
    id: 1,
    title: '001-KATJO',
    slug: 'katjo',
    img: '/asset/img/KATJO.svg',
    imgnoir: '/asset/img/KATJOnoir.svg',
    category: 'application',
  },
  {
    id: 2,
    title: '002-PL@NET',
    slug: 'pl@net',
    img: '/asset/img/KATJO1.svg',
    imgnoir: '/asset/img/KATJO1noir.svg',
    category: 'application',
  },
  {
    id: 5,
    title: '004-Brand Design',
    slug: 'branddesign',
    img: '/asset/img/KATJO4.svg',
    imgnoir: '/asset/img/KATJO4noir.svg',
    category: 'application',
  },
  {
    id: 3,
    title: '003-HESTIA',
    slug: 'hestia',
    img: '/asset/img/KATJO3.svg',
    imgnoir: '/asset/img/KATJO3noir.svg',
    category: 'application',
  },
  {
    id: 4,
    title: '005-SUPERMOOD',
    slug: 'supermood',
    img: '/asset/img/KATJO2.svg',
    imgnoir: '/asset/img/KATJO2noir.svg',
    category: 'application',
  },
];
